FROM ubuntu

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get install build-essential cmake python3 python3-pip curl
RUN pip3 install meson ninja

# make /bin/sh symlink to bash instead of dash:
RUN echo "dash dash/sh boolean false" | debconf-set-selections
RUN dpkg-reconfigure dash

RUN echo "--insecure" >> $HOME/.curlrc
RUN echo "--location" >> $HOME/.curlrc

RUN echo "" >> /etc/ssl/openssl.cnf
RUN echo "[system_default_sect]" >> /etc/ssl/openssl.cnf
RUN echo "Options = UnsafeLegacyServerConnect" >> /etc/ssl/openssl.cnf
RUN echo "Options = UnsafeLegacyRenegotiation" >> /etc/ssl/openssl.cnf
