FROM ubuntu

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends build-essential cmake gperf python3 python3-pip curl libx11-dev libxext-dev libz-dev
RUN pip3 install meson ninja docwriter

# make /bin/sh symlink to bash instead of dash:
RUN echo "dash dash/sh boolean false" | debconf-set-selections
RUN dpkg-reconfigure dash

RUN echo "--insecure" >> $HOME/.curlrc
RUN echo "--location" >> $HOME/.curlrc

RUN echo "" >> /etc/ssl/openssl.cnf
RUN echo "[system_default_sect]" >> /etc/ssl/openssl.cnf
RUN echo "Options = UnsafeLegacyServerConnect" >> /etc/ssl/openssl.cnf
RUN echo "Options = UnsafeLegacyRenegotiation" >> /etc/ssl/openssl.cnf

WORKDIR /app
